### ISSUE TITLE
Titan tensorflow container fails to build

### ISSUE THREAD

**Issue by markcoletti** [olcf/container-recipes#2]
I am unable to build the Titan tensorflow container.  The error is in the following build step:

```
ERROR: Could not build Bazel
The command '/bin/sh -c cd / &&     wget https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-dist.zip &&     unzip bazel-0.4.5-dist.zip -d /bazel &&     cd bazel &&     ./compile.sh &&     cd output &&     cp /bazel/output/bazel /usr/local/bin &&     rm -rf /bazel-0.4.5-dist.zip' returned a non-zero code: 1
Build Failed
```

This is the dump of what error messages I could see:

```
string JSMapGetterName(const GeneratorOptions& options,
       ^
INFO: From Compiling third_party/protobuf/3.0.0/src/google/protobuf/util/internal/utility.cc:
third_party/protobuf/3.0.0/src/google/protobuf/util/internal/utility.cc:50:19: warning: 'const google::protobuf::StringPiece google::protobuf::util::converter::{anonymous}::SkipWhiteSpace(google::protobuf::StringPiece)' defined but not used [-Wunused-function]
 const StringPiece SkipWhiteSpace(StringPiece str) {
                   ^
INFO: From Compiling third_party/protobuf/3.0.0/src/google/protobuf/util/internal/field_mask_utility.cc:
third_party/protobuf/3.0.0/src/google/protobuf/util/internal/field_mask_utility.cc:47:14: warning: 'google::protobuf::util::Status google::protobuf::util::converter::{anonymous}::CreatePublicError(google::protobuf::util::error::Code, const string&)' defined but not used [-Wunused-function]
 util::Status CreatePublicError(util::error::Code code,
              ^
INFO: From Compiling src/main/cpp/blaze_util_posix.cc:
src/main/cpp/blaze_util_posix.cc: In function 'void blaze::Daemonize(const string&)':
src/main/cpp/blaze_util_posix.cc:200:28: warning: ignoring return value of 'int dup(int)', declared with attribute warn_unused_result [-Wunused-result]
   (void) dup(STDOUT_FILENO);  // stderr (2>&1)
                            ^
src/main/cpp/blaze_util_posix.cc: In function 'uint64_t blaze::AcquireLock(const string&, bool, bool, blaze::BlazeLock*)':
src/main/cpp/blaze_util_posix.cc:499:30: warning: ignoring return value of 'int ftruncate(int, __off_t)', declared with attribute warn_unused_result [-Wunused-result]
   (void) ftruncate(lockfd, 0);
                              ^
src/main/cpp/blaze_util_posix.cc:504:47: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   (void) write(lockfd, msg.data(), msg.size());
                                               ^
INFO: From Compiling third_party/protobuf/3.0.0/src/google/protobuf/util/time_util.cc:
third_party/protobuf/3.0.0/src/google/protobuf/util/time_util.cc:378:6: warning: 'void google::protobuf::{anonymous}::ToUint128(const google::protobuf::Timestamp&, google::protobuf::uint128*, bool*)' defined but not used [-Wunused-function]
 void ToUint128(const Timestamp& value, uint128* result, bool* negative) {
      ^
third_party/protobuf/3.0.0/src/google/protobuf/util/time_util.cc:403:6: warning: 'void google::protobuf::{anonymous}::ToTimestamp(const google::protobuf::uint128&, bool, google::protobuf::Timestamp*)' defined but not used [-Wunused-function]
 void ToTimestamp(const uint128& value, bool negative, Timestamp* timestamp) {
      ^
INFO: From Compiling third_party/ijar/ijar.cc:
third_party/ijar/ijar.cc: In member function 'virtual bool devtools_ijar::JarStripperProcessor::Accept(const char*, devtools_ijar::u4)':
third_party/ijar/ijar.cc:66:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (filename_len >= CLASS_EXTENSION_LENGTH) {
                    ^
INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libbootstrap_JarOwner.jar [for host]:
warning: Implicitly compiled files were not subject to annotation processing.
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
1 warning
INFO: From Compiling src/main/cpp/blaze.cc:
src/main/cpp/blaze.cc: In member function 'virtual unsigned int blaze::GrpcBlazeServer::Communicate()':
src/main/cpp/blaze.cc:1692:80: warning: 'broken_pipe_name' may be used uninitialized in this function [-Wmaybe-uninitialized]
       fprintf(stderr, "\nCannot write to %s; exiting...\n\n", broken_pipe_name);
                                                                                ^
ERROR: /bazel/src/tools/android/java/com/google/devtools/build/android/ziputils/BUILD:20:1: Java compilation in rule '//src/tools/android/java/com/google/devtools/build/android/ziputils:ziputils_lib' failed: Worker process sent response with exit code: 1.
java.lang.InternalError: Cannot find requested resource bundle for locale en_US
        at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
        at com.sun.tools.javac.util.Log.localize(Log.java:673)
        at com.sun.tools.javac.util.Log.printLines(Log.java:485)
        at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:156)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
        at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:104)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:163)
        at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:52)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:166)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:178)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:90)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:44)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
        at com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:106)
        at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:125)
        ... 15 more
Target //src:bazel failed to build
INFO: Elapsed time: 156.492s, Critical Path: 134.74s

ERROR: Could not build Bazel
The command '/bin/sh -c cd / &&     wget https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-dist.zip &&     unzip bazel-0.4.5-dist.zip -d /bazel &&     cd bazel &&     ./compile.sh &&     cd output &&     cp /bazel/output/bazel /usr/local/bin &&     rm -rf /bazel-0.4.5-dist.zip' returned a non-zero code: 1
Build Failed

```

**Comment by AdamSimpson** [comment]
This appears related to https://github.com/bazelbuild/bazel/issues/4483 . Due to the cuda driver restricting the version of tensorflow and the version of tensorflow restricting the version of bazel i'll see what I can do about rolling back the jdk version used.

**Comment by markcoletti** [comment]
While you explore rolling back, I'll explore rolling bazel forward to its more recent version, 0.11.1.

**Comment by markcoletti** [comment]
bazel now builds, but it does whine:

```
WARNING: /tmp/bazel_Sn65u98e/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_Sn65u98e/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions
```

Build is proceeding.  I'll close this out when and if it finishes.

**Comment by markcoletti** [comment]
And, this is the latest error:

```
You have bazel 0.11.1- installed.
./configure: line 669: /usr/local/cuda/extras/demo_suite/deviceQuery: No such file or directory
Configuration finished
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
ERROR: /root/.cache/bazel/_bazel_root/05691b69ea8e69ef9e86d28a91a6ad71/external/io_bazel_rules_closure/closure/filegroup_external.bzl:23:16: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
ERROR: /root/.cache/bazel/_bazel_root/05691b69ea8e69ef9e86d28a91a6ad71/external/io_bazel_rules_closure/closure/compiler/closure_js_binary.bzl:216:13: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
ERROR: /root/.cache/bazel/_bazel_root/05691b69ea8e69ef9e86d28a91a6ad71/external/io_bazel_rules_closure/closure/compiler/closure_js_library.bzl:138:26: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
ERROR: /root/.cache/bazel/_bazel_root/05691b69ea8e69ef9e86d28a91a6ad71/external/io_bazel_rules_closure/closure/compiler/closure_js_deps.bzl:44:13: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
ERROR: error loading package '': Extension 'closure/compiler/closure_js_deps.bzl' has errors
ERROR: error loading package '': Extension 'closure/compiler/closure_js_deps.bzl' has errors
INFO: Elapsed time: 2.544s
FAILED: Build did NOT complete successfully (0 packages loaded)
The command '/bin/sh -c export PYTHON_BIN_PATH=`which python` &&     export PYTHON_LIB_PATH=/usr/lib/python2.7/dist-packages &&     export TF_NEED_MKL=0 &&     export CC_OPT_FLAGS="-march=native" &&     export TF_NEED_JEMALLOC=1 &&     export TF_NEED_GCP=0 &&     export TF_NEED_HDFS=0 &&     export TF_ENABLE_XLA=0 &&     export TF_NEED_OPENCL=0 &&     export TF_NEED_CUDA=1 &&     export TF_CUDA_CLANG=0 &&     export TF_CUDA_VERSION="7.5" &&     export CUDA_TOOLKIT_PATH="/usr/local/cuda" &&     export TF_CUDNN_VERSION="6" &&     export CUDNN_INSTALL_PATH=$CUDA_TOOLKIT_PATH &&     export TF_CUDA_COMPUTE_CAPABILITIES="3.5" &&     export TF_NEED_VERBS=0 &&     export TF_NEED_S3=0 &&     export TF_NEED_GDR=0 &&     export TF_NEED_OPENCL_SYCL=0 &&     export GCC_HOST_COMPILER_PATH=/usr/bin/gcc-4.9 &&     export TF_NEED_MPI=0 &&     export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$LD_LIBRARY_PATH &&     ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1 &&     cd / &&     wget https://github.com/tensorflow/tensorflow/archive/v1.3.1.tar.gz &&     tar xf v1.3.1.tar.gz &&     cd tensorflow-1.3.1 &&     ./configure &&     bazel build --local_resources 2048,2.0,1.0 -c opt --copt=-mavx --copt=-msse4.1 --copt=-msse4.2 --config=cuda tensorflow/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg &&     pip2 install /tmp/tensorflow_pkg/tensorflow-*.whl &&     cd / &&     rm -rf /v1.3.1.tar.gz &&     rm -rf /tensorflow-1.3.1 &&     rm -rf /tmp/tensorflow_pkg' returned a non-zero code: 1
Build Failed
[INFO] Finished streaming build
[ERROR] Container Builder exception encountered: Build failed with exit code 1
```

Not sure what to make of this.

**Comment by AdamSimpson** [comment]
I have fixed the issue by manually installing an appropriate JDK. As this is a mirror of an internal repository it will take an hour or two to sync up.
